# Generated by Django 4.1 on 2024-05-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("data", models.CharField(max_length=10)),
                ("photo", models.ImageField(upload_to="images")),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("surname", models.CharField(max_length=15)),
                ("age", models.CharField(max_length=10)),
                ("photo", models.ImageField(upload_to="images")),
                ("club", models.ManyToManyField(to="www.club")),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("photo", models.ImageField(upload_to="images")),
                ("player", models.ManyToManyField(to="www.player")),
            ],
        ),
    ]
