# Generated by Django 4.1 on 2024-05-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("www", "0002_rename_data_club_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="position",
            name="player",
        ),
        migrations.AddField(
            model_name="player",
            name="position",
            field=models.ManyToManyField(to="www.position"),
        ),
        migrations.AlterField(
            model_name="club",
            name="date",
            field=models.DateField(max_length=10),
        ),
    ]
