# Generated by Django 4.1 on 2024-05-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("www", "0003_remove_position_player_player_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="date",
            field=models.DateTimeField(max_length=10),
        ),
    ]
