# Generated by Django 4.1 on 2024-05-20 17:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("www", "0006_alter_club_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="position",
            name="photo",
        ),
    ]
